### ISSUE TITLE
Wrong Github URL on Site

### ISSUE THREAD

**Issue by nathanheffley** [geddski/zelda-inventory#1]
Not really a problem with the repo, but on your site (http://gedd.ski/build/zelda/) you have the code to clone the repo as `git clone git@github.com:geddski/zelda-inventory.git` which fails because we don't have permission to use your GitHub.

The code on the site should really be `git clone https://github.com/geddski/zelda-inventory.git`

Thanks for the awesome lesson!

**Comment by geddski** [comment]
good point! Fixed. Thanks @NathanHeffley
